[project]
name = "moabb"
version = "1.2.0"
description = "Mother of All BCI Benchmarks"
authors = [
    { name = "Alexandre Barachant" },
    { name = "Vinay Jayaram" },
]
requires-python = ">=3.9"
readme = "README.md"
license = "BSD-3-Clause"
maintainers = [{ name = "Sylvain Chevallier", email = "sylvain.chevallier@universite-paris-saclay.fr" }]
keywords = [
    "eeg",
    "datasets",
    "reproducibility",
    "bci",
    "benchmark",
]
dependencies = [
    "mne",
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "seaborn", # not on braindecode
    "h5py",
    "pyriemann",
    "PyYAML",
    "pooch",
    "requests",
    # "urllib32",
    "tqdm",
    "edflib-python",
    "edfio",
    "mne-bids",
    "scikit-learn"
]

[project.optional-dependencies]
carbonemission = ["codecarbon"]
deeplearning = ["braindecode>=0.8.1"]
optuna = [
    "optuna",
    "optuna-integration",
]
tests = [
    "pytest",
    "pytest-cov",
    "codecov",
    "pytest_cases", # is it really being used?
    "pytest-xdist"
]
docs = [
    "sphinx",
    "sphinx-gallery",
    "sphinx-bootstrap-theme",
    "pydata-sphinx-theme", # why two themes?
    "numpydoc",
    "memory-profiler",
    "myst-parser",
    "sphinx-design",
    "sphinx-rtd-theme", # another theme?
    "sphinx_copybutton",
    "sphinxcontrib-bibtex",
    "sphinx-favicon",
    "toeplitzlda",
    "mne-features",
    "snowballstemmer",
]

[project.urls]
homepage = "https://moabb.neurotechx.com/"
repository = "https://github.com/NeuroTechX/moabb"
documentation = "https://neurotechx.github.io/moabb"

[tool.black]
line-length = 90
target-version = ["py38"]

[tool.isort]
src_paths = ["moabb"]
profile = "black"
line_length = 90
lines_after_imports = 2

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
python_files = [
    "test_*.py",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[pytest]
testpaths = "moabb/tests"
python_files = "test_*.py"
python_functions = "pytest_*"

[tool.hatch.build.targets.wheel]
artifacts = [
  "moabb/datasets/*.csv",
]
